---
- name: Restart prometheus
  become: yes
  systemd:
    daemon_reload: yes
    name: prometheus
    state: restarted

- name: Reload prometheus
  become: yes
  systemd:
    name: prometheus
    state: reloaded
